apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: luvora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
        - name: api-gateway
          image: luvora-api-gateway:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Docker"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"