apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: luvora

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: luvora-frontend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

          env:
            - name: APP_ENV
              value: "local"

            - name: APP_DEBUG
              value: "true"

            - name: LUVORA_API_URL
              value: "http://api-gateway:8080"

            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: luvora-app-secret
                  key: APP_KEY
                  
            - name: SESSION_DRIVER
              value: "cookie"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10