services:

  postgres:
    image: postgres:17
    container_name: luvora-postgres
    environment:
      POSTGRES_USER: luvora
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: luvora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
