services:

  postgres:
    image: postgres:17
    container_name: luvora-postgres
    environment:
      POSTGRES_USER: ${env.POSTGRES_USER}
      POSTGRES_PASSWORD: ${env.POSTGRES_PASSWORD}
      POSTGRES_DB: ${env.POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
